version: '3.8'

services:
  # Configurando o serviço do aplicativo Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/quizapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db
    network_mode: bridge

  # Configurando o serviço do banco de dados PostgreSQL
  db:
    image: postgres:15.3-alpine
    network_mode: bridge
    environment:
      POSTGRES_DB: quizapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbdata: